#%RAML 1.0 DataType

description: Définition de la structure d'un object (liste de sélection)
type: object
properties:
  code:
    description: Le code (nom d'API salesforce) d'un élément d'une liste de sélection
    type: string
    example: "1"
  lbelle:
    description: La valeur d'un élément d'une liste de sélection
    type: string
    example: "libelle"